### PR TITLE
Fixed issues

### PR DESCRIPTION
**Pull request by RedDeadDepresso**
Hi, I solved the problem in auto_translate.py. The python file was in the root directory and was recently moved to develop_tools, so there were problems with the paths. You can run auto_translate.py by going to the root directory and running the following command in the terminal: 
``` 
python -m develop_tools.auto_translate 
``` 
I have already done this, so you don't have to do it again. However, I used google translate because papago didn't work for me. You are free to run the program again with papago if you want.

The only thing you need to do is use [qt linguist](https://github.com/thurask/Qt-Linguist/releases) and open gui/i18n/ko_KR.ts and check and edit the translations. Don't worry about being a faithful translation from Chinese, just make sure the message is clear. After that run the following commands: 
``` 
cd gui/i18n
lrelease ko_KR.ts 
```
 This will generate the binaries that will be used by the GUI.

### CODE REVIEW

**Comment by VoltIcaRus** [comment]
thx!!

**Comment by VoltIcaRus** [comment]
Thank you so much
Yes, I completed the first translation
I don't know with the translator alone, so I need to see the ui applied directly, so I tried to change the repo address, but it doesn't work
https://github.com/VoltIcaRus/Halo-Carrier-Arisu/blob/master/installer.py
repo
https://github.com/VoltIcaRus/Halo-Carrier-Arisu/
I changed it to but it didn't work

I don't know because the file structure is different from ArisuAutoSweeper
Like my fork in the Arisu AutoSweeper
I also need to add KR client (one store, teen version), but it's troublesome
Once this is done, I have an existing user and I'm going to let him know as well.

**Comment by RedDeadDepresso** [comment]
Unfortunately, I think blue_archive_auto_script is too hardcoded, so you can't run your fork directly from the binaries. You need to clone your fork on your PC and work on the source code.

Then run window.py and change the language to Korean in Settings to see the translations in the GUI. I'll try to give you a hand to add KR client.

**Comment by VoltIcaRus** [comment]
idk 
When I run windows py, the cnocr module is not installed and an error occurs
Yes so I was going to install it but polygon3 installation always makes errors and I searched hard to fix this
image

```Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX86\\x86\\link.exe' failed with exit code 1120
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Polygon3
  Running setup.py clean for Polygon3
Failed to build Polygon3
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (Polygon3)
```
```
Building wheels for collected packages: Polygon3
  Building wheel for Polygon3 (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Using NumPy extension!
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win32-3.9
      creating build\lib.win32-3.9\Polygon
      copying Polygon\IO.py -> build\lib.win32-3.9\Polygon
      copying Polygon\Shapes.py -> build\lib.win32-3.9\Polygon
      copying Polygon\Utils.py -> build\lib.win32-3.9\Polygon
      copying Polygon\__init__.py -> build\lib.win32-3.9\Polygon
      running build_ext
      building 'Polygon.cPolygon' extension
      creating build\temp.win32-3.9
      creating build\temp.win32-3.9\Release
      creating build\temp.win32-3.9\Release\src
      C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DDEFAULT_STYLE=STYLE_LIST -DWITH_
NUMPY=1 -DSYSTEM_WIN32=1 -Isrc -IC:\users\appdata\local\programs\python\python39\lib\site-packages\numpy\core\include -IC:\users\appdata\local\programs\python\python39\include
-IC:\users\\appdata\local\programs\python\python39\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22
621.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt -IC:\Program Files (x86)\Windows Kits
\10\\include\10.0.22621.0\\cppwinrt -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Win
dows Kits\10\include\10.0.22621.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um -IC:\Program Fi
les (x86)\Windows Kits\10\include\10.0.22621.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\cppwinrt /Tcsrc/PolyUtil.c /Fobuild\temp.win32-3.9\Release\src/PolyUtil.o
bj
      PolyUtil.c
      C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\corecrt.h(10): fatal error C1083: 포함 파일을 열 수 없습니다. 'vcruntime.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.40.33807\\bin\\Hostx64\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Polygon3
  Running setup.py clean for Polygon3
Failed to build Polygon3
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (Polygon3)

```
I don't know why it's so complicated 
Just to test 
Blocked from cnocr installation and I can't figure out why polygon3 installation isn't working fk
 
It's so hard to organize the environment 
How did you do this

**Comment by VoltIcaRus** [comment]
image
Notes
Someone will go through the same process as me, you need to install from native and not run from powershell

**Pull request merged**
