### PR TITLE
fixed kr one translation in gui

### PR DESCRIPTION
**Pull request by RedDeadDepresso**
You forgot to run the lrelease command

### CODE REVIEW

**Comment by RedDeadDepresso** [comment]
Other than that, everything else works, right?

**Comment by VoltIcaRus** [comment]
I can't get the app to run, I need to look at it. 

```
no predefined vocab_fp is found for model ('densenet_lite_114-fc', 'onnx'), use the default C:\Users\\AppData\Local\Programs\Python\Python39\lib\site-packages\cnocr\label_cn.txt
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)

```
I also see this error, but it doesn't matter for now

**Comment by VoltIcaRus** [comment]
ERROR | 2024-07-20 00:12:37 | [WinError 2] The specified file could not be found 
   ERROR | 2024-07-20 00:12:37 | Emulator start failed
   CRITICAL | 2024-07-20 00:12:37 | Initialization Failed 
   I think 
   Ineed to fix this first. 
   
   
image

And I need the student list and stage name to be in English, I am looking for the related code

**Comment by VoltIcaRus** [comment]
Okay, the app has successfully launched 
The list is in Chinese and the 
just need to fix some translations

**Pull request merged**
